### ISSUE TITLE
Feature: Push to Talk when muted

### ISSUE THREAD

**Issue by Dletta** [meething/meething#105]
One feature I like on Zoom calls is pushing space when you are muted to be able to respond but stay muted.

**Comment by lmangani** [comment]
We actually have an ace up our sleeve. Actual push to talk though DAM/Gun @QVDev already developed and we're planning to reintroduce in a really creative way.

**Comment by Dletta** [comment]
Yeahh!!

**Comment by lmangani** [comment]
Temporary solution would be to attach the spacebar to mute
```
/* keyboard shortcuts */
    document.body.onkeyup = function(e){
       e.preventDefault();
       if(e.keyCode == 32){
        // audioMuteCode
       }
    }
	  
```

**Comment by jacovinus** [comment]
take a look at [spacebar - mute](https://github.com/meething/meething/commit/df417b093ca7c0bf924df1e16c364d1b9268dcbc)

**Comment by Dletta** [comment]
It’s working, awesomely!!
Close?

**Comment by jacovinus** [comment]
Feature working on app, closed.
