### ISSUE TITLE
Fix toggles

### ISSUE THREAD

**Issue by QVDev** [meething/meething#112]
Uncaught (in promise) DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided ('fas fa-video') contains HTML space characters, which are not valid in tokens.
    at https://meething.hepic.tel/assets/js/rtc.js:897:34

**Comment by jacovinus** [comment]
I propose switching to Ionicons for solving this and improving UI:

Pros: 
+ no empty spaces needed
+ lighter weight than font awesome
+ Outline, filled and sharp variants all free
+ looks better 

Cons: 
- another js file attached (mandatory for every icons system)
- different usage  ```<ion-icon name="log-in-outline"></ion-icon>```
