### ISSUE TITLE
Add chat toggle / actions

### ISSUE THREAD

**Issue by QVDev** [meething/meething#113]
The toggles / buttons on top right become to many.

This means debug toggles should be moved somewhere else my suggestion is to use chat commands.

The first one will be help with the options and then we can extend from there.

This way we can move debug toggles oit of the way and have only important buttons

**Comment by Dletta** [comment]
All for that!!

**Comment by jabis** [comment]
For mobile I'd suggest one button to rule them all - click an action button and have an ordered list of actionable buttons to select from

**Comment by jabis** [comment]
oh - ps - cool buttons required!

**Comment by jacovinus** [comment]
Will do a top and bottom menu for that

**Comment by Dletta** [comment]
Technically done??

**Comment by QVDev** [comment]
Indeed done deal
