### ISSUE TITLE
Username not under the video

### ISSUE THREAD

**Issue by QVDev** [meething/meething#143]
Sometimes you see name sometimes you see the socket id

**Comment by Dletta** [comment]
Fixed with PR #151

**Comment by Dletta** [comment]
It does take a few seconds, then controlData is received, which changes the name

**Comment by Dletta** [comment]
Okay more than a few seconds, not sure what triggers it, but it does update now. We might need to find a place to call med.metaData.sendControlData earlier in the process. :)
