### ISSUE TITLE
once joined room undefined

### ISSUE THREAD

**Issue by QVDev** [meething/meething#146]
If you joined once the room and refresh the page without room name it say room undefined

**Comment by lmangani** [comment]
This also allows users joining an non-existing room

**Comment by lmangani** [comment]
Patch goes [here](https://github.com/meething/meething/blob/c336f4bc39f4143a89993bf2baf4854164ddf1fd/src/assets/js/modal.js#L76) but I'm not sure where the roomid lives anymore :)

**Comment by lmangani** [comment]
Ok I get it now perhaps for @Dletta the username is stored in sessionStorage but the roomId is not - when exiting the room the roomId is gone from the URL and the app knows no better.

**Comment by Dletta** [comment]
#140 will resolve this
