### ISSUE TITLE
Screenshare is full fledge quality

### ISSUE THREAD

**Issue by QVDev** [meething/meething#149]
Currently we sending it without adjustment but we can change it to what we do with video

**Comment by lmangani** [comment]
@QVDev will do - could you point me at the code establishing the producer?

**Comment by QVDev** [comment]
Jep line 86 in sfu.js you also did the normal video but those are not working for screen share :)

**Comment by lmangani** [comment]
https://github.com/meething/meething/pull/155 MIGHT be enough to fix it, needs testing
