### ISSUE TITLE
Gridstack Videowall

### ISSUE THREAD

**Issue by lmangani** [meething/meething#15]
It should be quite trivial (and fun?) migrating the current video layout into gridster and let users arrange and modify video streams as they see fit. Should only need basic grid, and a couple functions to add/remove the blocks containing remote user video.

https://gridstackjs.com/#demo

Up for grabs if anyone likes the idea and feels like it!

**Comment by jabis** [comment]
Seems like a good idea 👍

**Comment by lmangani** [comment]
Great! We could also place the chat and other items in the grid, make it fully liquid

**Comment by Dletta** [comment]
We got a good solution right now, closing this since it's outdated
