### ISSUE TITLE
We should be able to have mesh and SFU work together

### ISSUE THREAD

**Issue by QVDev** [meething/meething#167]
When a person joins from mesh or SFU should not matter they still should be able to join the party. We call this hybrid on steroids. So not only either or but both at the same time.

2 peers SFU 1 person Mesh
3 peers Mesh 1 person SFU? Is this even possible I just thinking. As I will be force to use p2p :) but guess that should happen automatically we end up in 4 people mesh 0 SFU

**Comment by QVDev** [comment]
@Dletta is this still valid after we have the toggle in the newOptions?

**Comment by Dletta** [comment]
For now keeping them separate is fine
