### ISSUE TITLE
Flip user videos horizontally

### ISSUE THREAD

**Issue by thrownness** [meething/meething#18]
Hard to explain, but for some reason, the user is accustomed to seeing their video flipped horizontally. Perhaps this is because most selfie cameras show the user video this way.

Right now in the app, the video presents the user video the other way.

**Comment by amirsanni** [comment]
This can be corrected by adding some CSS to the local video element. The below should suffice.

```
.local-video{
    -ms-transform: scaleX(-1);
    -moz-transform: scaleX(-1);
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
}
```

**Comment by QVDev** [comment]
I saw the PR but I havent need seen why this is usefull can we have more info? As I see my local stream is the opposite that people see me. So point left for me will be the otherway when people see me
