### ISSUE TITLE
Cross Site Scripting

### ISSUE THREAD

**Issue by InformationArchitect** [meething/meething#187]
**Describe the bug**
Javascript works when sent as an iframe in chat. User inputted JS should not be evaluated under any circumstances.

**To Reproduce**
1. Go to https://us.meething.space
2. Create a room with multiple instances
3. Paste this in chat
`<iframe src="https://us.meething.space" title="hax"></iframe>`
4. See security error

**Expected behavior**
Any attempt at entering js in chat should fail or not evaluate on another client.

**Screenshots**
![image](https://user-images.githubusercontent.com/12848421/83181768-5f06ce00-a0f3-11ea-8230-0929e4146cdf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**
- Link you used? 
https://us.meething.space
- Branch you used? (Such as fix_audio)
master?

- [x] Cross site scripting

**Comment by Dletta** [comment]
I like the evil hacker face, ;)
