### ISSUE TITLE
Test hosting on Vercel?

### ISSUE THREAD

**Issue by kcsf** [meething/meething#214]
Hello,
BRILLIANT platform!

We'd like to test it out; can it be hosted on Vercel.com.
If so, what is the build command?

Thanks!

**Comment by QVDev** [comment]
HI @kcsf thanks for the interest, I looked quickly at Vercel and it seems to host static website right? Not nodejs stuff? In the meanwhile I will have a look into it and try to get it running. But in general we should be able to host this also on github pages. So Vercel should in theory be possible. Let me know for what your usecase is and I can help you out.

**Comment by QVDev** [comment]
@kcsf We are now working on making the repository deployable as a static webpage for Github pages that seem to work nicely after that Vercel.com should work out of the box for you.

**Comment by QVDev** [comment]
Meething is now deployable for static hosting

**Comment by kcsf** [comment]
Great, thankyou..  We put our test up on heroku for now, may circle back
later and see if vercel works.

--

Casey Jeppesen
CTO - eCovalence, LLC.
www.eCovalence.com
GVoice: 386.243.2628 <386-243-2628>
Mobile: 415.656.6275

**Comment by QVDev** [comment]
@kcsf you please do come back report the outcome as we might want to use it as well to streamline development and testing. Much appreciated 👍
