### ISSUE TITLE
Remote Video Gets Disconnected After Certain Time 

### ISSUE THREAD

**Issue by harivyas35** [meething/meething#231]
Hi ,
I have deployed this app the link is -  https://myhari-dsw0yrb3n.vercel.app  
After Joining the call the participant's video gets disconnected after 2-3 mins and the first participant who started the meeting sees two video elements . But  after checheck  i can see that all the participants are present in the meeting. Can you please help me .

Regards,
Hari Vyas

**Comment by Dletta** [comment]
Hi @harivyas35,

This just happened to me on glitch. We are looking into it.

**Comment by jabis** [comment]
This is a known thing to happen when your `turn` server gives up a connection based on timeout

**Comment by harivyas35** [comment]
Hi @Dletta ,
Thank you for your reply.
Regards,
Hari Vyas

**Comment by jabis** [comment]
@harivyas35 You could try setting your own (for example) `coturn` instance yes, and replace the iceServers in helpers.js file.

**Comment by jabis** [comment]
Closing this issue as I think the author got it handled - feel free to re-open if you can repeat
