### ISSUE TITLE
Week Goals (to be revised)

### ISSUE THREAD

**Issue by amark** [meething/meething#25]
this is what had put in submission cause we needed to say something, haha, of course can be revised:

Splitting into 2 sub teams, Product & Infrastructure.

Week -1: Lorenzo built a working video conference prototype with GUN as experiment. https://github.com/meething/webrtc-gun

Week 0: Organized team, do calls, assign roles, submit this application. (Now)

Week 1: Kshitij, Cale, Alex get https://github.com/justadudewhohacks/face-api.js up & running on a simple test page to familiarize themselves with API. Mark, Lorenzo, Dirk familiarize with intercepting Video streams while still feeding it to WebRTC & SFU.

Week 2: Product team makes a PR for ugly integration of face tracker into Meething repo. Infra team connects video streams to it.

Week 3: Product team tests that it works & gets user feedback on UX improvements. Infra team tests using GUN to control SFU relays.

Week 4: Product team cleans up UX. Infra team deals with networking disasters & delays.

Week 5: Product team polishes experience. Infra team debugs dropped connections & hiccups.

Week 6: Test, test test.

Week 7: Product team refactors code for better browser/device compatibility. Infra team fine-tunes default down-sampling rates on video streams to match real world bandwidth limits.

Week 8: Prepare splash page, presentation, pitch, and demo. Fix last minute bugs/features.

**Comment by QVDev** [comment]
@amark I see in week 1 intercepting video stream what do we mean with this?

**Comment by QVDev** [comment]
Week one spoiler alert to speed things up for face api 

https://medium.com/@medooze/adding-metadata-to-media-frames-via-insertable-streams-api-for-webrtc-47f7a740e457

Here is an example 

https://sgmedooze.cosmosoftware.io/insertable-face/index.html

**Comment by Dletta** [comment]
Spoiler Alert, ;). Needs chrome with special flag enabled

**Comment by lmangani** [comment]
@Dletta not really, it doesn't for our usecase we are only interested in the part of the code that gets the face position and we can stream it using our own channels. There's no need for Chrome or even any special webRTC feature as in the demo, it just happens to prove the same point. I tested with any browser the facedetection part works and the position is avialable for streaming out via GUN ;)

**Comment by Dletta** [comment]
Nice. That makes it achievable for Week 7-8

**Comment by lmangani** [comment]
Closing as no longer reflecting the status - see github project page for the new stack
