### ISSUE TITLE
How to deploy this meething in online web servers

### ISSUE THREAD

**Issue by siddharthdeo99** [meething/meething#256]
How to deploy this meething in online web servers.

**Comment by QVDev** [comment]
Hi @siddharthdeo99 it can run static if you want meaning you can just download the source and deploy it on static html server. 

If you have node server look at the readme where it is explained. 

Is this info suficiant?

**Comment by siddharthdeo99** [comment]
@QVDev If i upload this as static website will it meeting work? 
i mean if I'm able to send links and join my friends?

**Comment by QVDev** [comment]
Yes definitly that will work. If you want you can fork it and make your repo use github pages and it works!

**Comment by siddharthdeo99** [comment]
Thanks ☺️
