### ISSUE TITLE
Recording Video

### ISSUE THREAD

**Issue by QVDev** [meething/meething#36]
As we go along we would like to record the meetings hold on meething app.

**Comment by lmangani** [comment]
https://github.com/muaz-khan/RecordRTC

**Comment by amirsanni** [comment]
https://github.com/amirsanni/video-call-app-nodejs.

**Comment by lmangani** [comment]
@amirsanni is recording (to disk) the conference a feature you already have/had?

**Comment by amirsanni** [comment]
Yes though you either record just yourself or your screen. It can easily be extended to have all participants recorded and do whatever you want with the file.

**Comment by lmangani** [comment]
Thanks @amirsanni - if you could outline the relevant parts, we'll port them in.

**Comment by amirsanni** [comment]
Sure.

**Comment by amirsanni** [comment]
Check out this [commit](https://github.com/amirsanni/Video-Call-App-NodeJS/commit/66a954648221793eac46162dc83caeea60c1d12e).

![Screenshot_20200419-232625_Chrome](https://user-images.githubusercontent.com/6107185/79701514-ad73b200-8295-11ea-849b-514141a4d80e.jpg)

**Comment by amirsanni** [comment]
The main recording functionality happens in `rtc.js`. `helpers.js` handles saving of the recorded stream.

**Comment by QVDev** [comment]
https://t-mullen.github.io/video-stream-merger/ this could help a lot as well

**Comment by QVDev** [comment]
https://slides.com/twoxaa/woah-is-that-offscreencanvas/fullscreen#/0/12

**Comment by QVDev** [comment]
Done deal for active speaker
