### ISSUE TITLE
WEEK 1 : Research, Planning and Getting to Know 

### ISSUE THREAD

**Issue by Dletta** [meething/meething#37]
// Edit 'Added Bert Nerd' Persona
Hi Team,

It’s **Week 1 of the Mozilla Spring MVP Lab** and that means we are gathering ideas, making sketches, thinking about and researching possible feature sets.

**State so far:**
- Pretty Stable Video Conferences for small groups (@alexios is working on quantifying how stable and how many people)
- We can mute mic, we can turn video off and I think we can turn them back on 😉 
- We have a list of active users and can display their id’s (usernames to come) in the video stream and in a list of users
- We can lock a room so no new person can join and implementing unlock in the next couple days (4/21)

**Where are we going:**

This week is for our team to gather features, assign work, do some research on what technologies (libraries, functionalities, webRTC) to use and to setup calls to get to know each other and share ideas.

Hopefully that will result in a backlog of features we can develop and work on in the remaining 7 weeks.
There is lots of activity between @QVDev , @lmangani and @jabis. We don’t want to interrupt that, but we do want ideas from all sides so we can agree on an outlook we all can commit to and feel we can contribute to.

**Personas**

To help us in ideation for the Product I recommend using Personas to help guide our work to be focused on specific possible users of our system.

- **Granny Smith** - She is of the older generation and will mainly receive invites from her family to join calls. Her eyesight might not be perfect, she needs a bit of help making sure she isn’t on mute or that others can see her. 
- **Joe Clark** - Corporate CTO who wants his remote teams to work together better. He’s looking at making sure people can focus and aren’t distracted, but also that information about his companies secrets aren’t stolen in the process.
- **Ari Obianwu** - Citizen Journalist in an oppressive country. He needs a secure way to communicate with sources and news papers around the globe, without having to reveal his real identity. He needs a way to share information aka files, screenshots or just screen share without compromising on his own safety.
- **Sandy Teen** - She loves hanging out with friends. She needs a way to quickly connect with a set of friends to organize parties or just hang out. The less hassle the better. She does want to use this system to communicate with her Granny and doesn’t want to get frustrated by having to say “Push the red button on the bottom” 50 times.
- **Arthur PHD Student** - He wants to quickly connect with researchers across the globe to discuss his findings. He needs to share his screen, flip to the camera and share files.
- **Bert Nerd** - Loves stats and seeing how the network works. Wants to see his internet and browser work the magic. Wants to know packets lost and bandwith and connection .... everything he can get to see.

Personas are a good way to keep the people who would use this product in mind. These aren’t set in stone of course and can be further detailed as we go. They should at least partially reflect someone we know and can sympathize with. Especially on UI.

Major Features that come to mind looking at these:
- Secure Video and Audio Transmission (Encryption ? / Peer-to-Peer without interceptors ?)
- Good UX that has visible indicators when you are on mute or when your camera is off.
- A shared whiteboard for collaboration (stretch goal?)
- Screen Share with “Entire Screen” and “Only select Window” mode
- One Click Meeting Start, Default Name remembered
- Calling Granny Mode, gives you control to unmute and turn camera on (stretch goal? Can also be host permissions instead of Granny Mode)
- File Sharing (Mozilla already has a service to send files, maybe it has an API -> Research; stretch goal?)
- Auto Arranging Multi-Party Videos, freedom to move them around etc.

**Kickoff / Conclusion**

Let’s discuss here. I think the idea is not to merely build a clone of zoom or other already existing products.
Let’s build something unique on the technology @QVDev  and @lmangani  have worked so hard to punch out over the last year (or two), and let’s make it our own.

Let’s get to work!!

![Inspirational Quote1](https://i.pinimg.com/736x/b7/4f/82/b74f82f088df3dd0fd855355f1f5526a.jpg)

**Comment by QVDev** [comment]
@Dletta thanks looking good in first sight. Here are my first comments:

1. Regarding the state mute/unmute is not working for multiple people. 
2. Like the granny one, simplicity and stability. It should just work. And the Journalist.
3. Like the features some indeed are a stretch but think we can discuss priority and maybe make them smaller if we think they are important.

Nice list, do we also want to document way of work? Such as:
- How do communicate status, such as finished work, stuck and need help or need more time?
- Workflow for programmers? Branching pull request etc..

**Comment by QVDev** [comment]
Like to have as mentioned as in discord "nerd" stats bandwidth usage etc.. and connectivity graph. Just putting it here

**Comment by InformationArchitect** [comment]
On the topic of short term (this week) QA testing Im hoping to do enough at a set time every week in order to be able to be up to date on any emerging friction or sticky bugs if I regularly use it when meeting with mentors. I feel it will help them understand our progress better and be more present with what we still need to achieve. Input?

**Comment by QVDev** [comment]
Nice research to look at discussions of competitors feature requests from users.

https://devforum.zoom.us/c/feature-requests

https://community.ringcentral.com/ringcentral/categories/ringcentral_rc_meetings?topic-list[settings][sort_on]=reply_count&topic-list[settings][type]=idea

Feel free to add more and pick out ideas to get inspired from

**Comment by Dletta** [comment]
Added Bert Nerd Persona. Reading research.

**Comment by Dletta** [comment]
Summary of research:
- A lot of feature request on both ring and zoom are integration related
- A few are about specific settings like 'Guests can join before host' or 'Co Hosting rights'
- Linux compatibility or Chromebook compatibility (we got those covered)
- Interestingly, the video feed mirroring was found here. It looks like what the users wanted was to not mirror their own view of themselves, but mirror the view going out to others for dance classes, school instruction (aka written words or whiteboard would show mirror to people viewing the video)
https://devforum.zoom.us/t/broadcast-of-mirror-image/208/10
- Scheduling meetings ahead of time (this is more the 'enterprise' case)
- Storing call recordings in the cloud (ipfs? gundb?)
- Pausing / Resuming Recordings
- Breakout Rooms (sounds interesting)
- Telephone into the meeting (how would one do this decentralized?)
- Inserting a custom logo in the channel (small customization for the host to make ahead of meeting)
- Polls
- Printable Attendee list
- Password Protection for meeting
- File Transfer (Mozilla has https://send.firefox.com/ maybe an integration?)

**Comment by QVDev** [comment]
@Dletta Funny you found that flip camera view there :) guess we can bring that back to the table :)

**Comment by lmangani** [comment]
@Dletta @QVDev this type of functionality should be implemented in the Video button stack per each participant (we're working on it) so we can have this preference handy but not too critical. Sounds like a personal preference and nothing more based on the content/purpose not a feature.

**Comment by Dletta** [comment]
Definitely something for a future backlog, not a MVP candidate. 
I think towards end of this week we should focus on getting an MVP backlog up into the GitHub Project. Things we all want in the project and think we can achieve in 8 weeks, plus a few stretch goals.

That way we can focus on those and talk each week about how we are doing in respect to that.

**Comment by Dletta** [comment]
Closing this as Project handles these
