### ISSUE TITLE
Speak detection

### ISSUE THREAD

**Issue by QVDev** [meething/meething#58]

**Comment by lmangani** [comment]
This is already provided by the pc sockets `.getStats` which emits the amplitude of the signal of the remote party alongside many other metrics - I will import some code to handle it.

**Comment by lmangani** [comment]
Here are two examples, almost identical: 

- [stream volume](https://webrtc.github.io/samples/src/content/getusermedia/volume/)
- [soundmeter.js](https://github.com/medooze/sfu/blob/master/www/js/soundmeter.js)

```
const stream = await navigator.mediaDevices.getUserMedia({audio: true, video: false });
var soundMeter = new SoundMeter(window);
	//Stop
	cancelAnimationFrame(drawTimer);

	function draw() {
		drawTimer = requestAnimationFrame(draw);

		now = Date.now();
		delta = now - then;

		if (delta > interval) {
			then = now ;
			var tot = Math.min(100,(soundMeter.instant*200));
			//Get all 
			const voometers = document.querySelectorAll (".voometer");
			//Set new size
			for (let i=0;i<voometers.length;++i)
				voometers[i].style.width = (Math.floor(tot/5)*5) + "%";
		}
	
	}
	soundMeter.connectToSource(stream).then(draw);
```

**Comment by QVDev** [comment]
Like the stats one dont think we want display volume meter right?

**Comment by lmangani** [comment]
well, actually we might want to display user activity and/or use the threshold it to move widgets to "active" speaker etc?

**Comment by Dletta** [comment]
I need to check out those stats, looks like we could nerd out on those.

I think having some kind of speech indicator is great. @lmangani Any of this helpful to clean small noise?

**Comment by lmangani** [comment]
@Dletta not really this is just emitting a bunch of data including the Amplitude of the signal as per demo. It can be used to move the speaker to active and/or add/remove classes to a little sound indicator to blink or whatever. It has no impact or interaction with the audio and should not as that's really heavy lifting we can't afford in mesh mode on the poor browser, although if we measure Heavy Metal for x cycles we could auto-mute or whatever - much later in time :)

**Comment by lmangani** [comment]
Implemented.
