### ISSUE TITLE
Safari, Safari & Chrome on iOS fail to load video 

### ISSUE THREAD

**Issue by jabis** [meething/meething#60]
Related: #56
I suspect the stream handling with MediaStream constructor is of issue here (unsupported in Safari/Safari on iOS)

Will need people with iPhones/iPads to test, I have none ;(

**Comment by Dletta** [comment]
I can test and wirk with you on implementing

**Comment by QVDev** [comment]
This still valid?

**Comment by Dletta** [comment]
Wirks on my iPhone
