### ISSUE TITLE
Vertical 'centering' on widgets

### ISSUE THREAD

**Issue by Dletta** [meething/meething#71]
When @QVDev and I were dogfooding, I noticed his image would shift to the right when I didn't quite use the right widget location in grid. 

Looked like canvas is left aligned and gets cut off on the right, making it appear out of center. If I stretched to use 2 colums, it usually was only 1 row high, which cut some of his face off at top and bottom.

Will take a picture and add here if I see it again.

**Comment by lmangani** [comment]
The grid is being replaced to address this and other issues so I'll close this one and ask to retest once we release.
