### ISSUE TITLE
Record just 'the thing I missed' (30 seconds in the past)

### ISSUE THREAD

**Issue by Dletta** [meething/meething#72]
An idea from my wife.

"What if you just missed something and you wanted to take a quick saving of the last 30 seconds you missed. You should have a button for that."

**Comment by lmangani** [comment]
Sounds like a perpetual interception.... Just personal opinion but this is nearly impossible without wasting a ton of space, performance, and would be totally anti privacy unless we implement a "do you accept to be recorded" feature as well :)  :)

**Comment by Dletta** [comment]
Yeah, that's what my first thought was, unless it's a limited buffer, that overwrites itself as it goes
for exactly 30 seconds.
