### ISSUE TITLE
Request: No ask name to join room, just join room instantly (optionally set name). Yeah?

### ISSUE THREAD

**Issue by amark** [meething/meething#74]

**Comment by lmangani** [comment]
This should be optional - we need room settings upon creation, as well as a screen to let the user decide if they want to join with any device muted. One of the MAJOR flaws of Zoom has been unauthorized access to rooms and we should make sure our design not deficient on protecting the users (all of them)

**Comment by lmangani** [comment]
Closing to keep the stack clean, feel free to raise this up in a future milestone!
