### ISSUE TITLE
video does not work

### ISSUE THREAD

**Issue by MidaAiZ** [meething/meething#83]
platform: macOs
browser: chrome
problem: I started the server and joined a room, but nothing happened. No video, no sound. There was no meeting stream created when joining the room. 
![image](https://user-images.githubusercontent.com/20530529/80405396-235ec580-88f5-11ea-8623-0370b4cc47fc.png)

**Comment by MidaAiZ** [comment]
![image](https://user-images.githubusercontent.com/20530529/80405470-3d98a380-88f5-11ea-98f4-a3f2bf66129d.png)

**Comment by lmangani** [comment]
The video only starts when a second participant joins, Having no self-view active suggests this was probably not the case - Was this with one or two participants? If not, try two browser windows. but the logs suggest you also had issues connecting to a Gun peer. Could you attach the logs separately from the image as text?

**Comment by lmangani** [comment]
Please reopen if you tried and failed with minimum 2 browsers. If this was the case, we'll add a notification "waiting for other participants" to avoid any user confusion.

Thanks for your report!
